// <auto-generated />
using System;
using BnpCashClaudeApp.Persistence.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnpCashClaudeApp.Persistence.Migrations
{
    [DbContext(typeof(NavigationDbContext))]
    [Migration("20251216081628_AddPersianDateColumns")]
    partial class AddPersianDateColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrpCode")
                        .HasColumnType("int");

                    b.Property<int>("TblUserGrpIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("TblUserGrpIdLastEdit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ZamanInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanInsertShamsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ZamanLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanLastEditShamsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblGrps");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrpMenu", b =>
                {
                    b.Property<int>("tblGrpId")
                        .HasColumnType("int");

                    b.Property<int>("tblMenuId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TblUserGrpIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("TblUserGrpIdLastEdit")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZamanInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanInsertShamsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ZamanLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanLastEditShamsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tblGrpId", "tblMenuId");

                    b.HasIndex("tblMenuId");

                    b.ToTable("tblGrpMenus");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMenu")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TblUserGrpIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("TblUserGrpIdLastEdit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ZamanInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanInsertShamsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ZamanLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanLastEditShamsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("tblMenus");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordLastChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TblUserGrpIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("TblUserGrpIdLastEdit")
                        .HasColumnType("int");

                    b.Property<int?>("UserCode")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ZamanInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanInsertShamsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ZamanLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanLastEditShamsi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUserGrp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TblUserGrpIdInsert")
                        .HasColumnType("int");

                    b.Property<int?>("TblUserGrpIdLastEdit")
                        .HasColumnType("int");

                    b.Property<DateTime>("ZamanInsert")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanInsertShamsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ZamanLastEdit")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZamanLastEditShamsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tblGrpId")
                        .HasColumnType("int");

                    b.Property<int>("tblUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("tblGrpId");

                    b.HasIndex("tblUserId", "tblGrpId")
                        .IsUnique();

                    b.ToTable("tblUserGrps");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrpMenu", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "tblGrp")
                        .WithMany()
                        .HasForeignKey("tblGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", "tblMenu")
                        .WithMany("GroupMenus")
                        .HasForeignKey("tblMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblGrp");

                    b.Navigation("tblMenu");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUserGrp", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "tblGrp")
                        .WithMany()
                        .HasForeignKey("tblGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", "tblUser")
                        .WithMany()
                        .HasForeignKey("tblUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblGrp");

                    b.Navigation("tblUser");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("GroupMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
