// <auto-generated />
using System;
using BnpCashClaudeApp.Persistence.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnpCashClaudeApp.Persistence.Migrations
{
    [DbContext(typeof(NavigationDbContext))]
    [Migration("20260106114412_AddTblShobeTable")]
    partial class AddTblShobeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GrpCode")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblGrps_PublicId");

                    b.ToTable("tblGrps");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrpPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GrantedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblGrpId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblPermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tblPermissionId");

                    b.HasIndex("tblGrpId", "tblPermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblGrpPermissions_tblGrpId_tblPermissionId");

                    b.ToTable("tblGrpPermissions", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMenu")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblMenus_PublicId");

                    b.ToTable("tblMenus");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenuPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblMenuId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblPermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tblPermissionId");

                    b.HasIndex("tblMenuId", "tblPermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblMenuPermissions_tblMenuId_tblPermissionId");

                    b.ToTable("tblMenuPermissions", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblPermissions_PublicId");

                    b.HasIndex("Resource", "Action");

                    b.ToTable("tblPermissions", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("ShobeCode")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblShobes_PublicId");

                    b.HasIndex("ShobeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_tblShobes_ShobeCode");

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("tblShobes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginAt")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaEnabledAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaLastUsedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordLastChangedAt")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserCode")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblUsers_PublicId");

                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUserGrp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignmentDate")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblGrpId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tblGrpId");

                    b.HasIndex("tblUserId", "tblGrpId")
                        .IsUnique();

                    b.ToTable("tblUserGrps");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.CryptographicKeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DestroyedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestructionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EncryptedKeyValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptionIV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GracePeriodEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KeyLengthBits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PreviousKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReplacedByKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("IX_CryptographicKeys_KeyId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_CryptographicKeys_PublicId");

                    b.HasIndex("Purpose")
                        .HasDatabaseName("IX_CryptographicKeys_Purpose");

                    b.HasIndex("Purpose", "Status")
                        .HasDatabaseName("IX_CryptographicKeys_Purpose_Status");

                    b.ToTable("CryptographicKeys", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.PasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SetAt")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordHistory_PublicId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PasswordHash");

                    b.ToTable("PasswordHistory", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_PublicId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRevoked", "IsUsed");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.SecuritySetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_SecuritySettings_PublicId");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SecuritySettings", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrpPermission", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "tblGrp")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("tblGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", "tblPermission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("tblPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblGrp");

                    b.Navigation("tblPermission");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenuPermission", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", "tblMenu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("tblMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", "tblPermission")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("tblPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblMenu");

                    b.Navigation("tblPermission");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUserGrp", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "tblGrp")
                        .WithMany("UserGroups")
                        .HasForeignKey("tblGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", "tblUser")
                        .WithMany()
                        .HasForeignKey("tblUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblGrp");

                    b.Navigation("tblUser");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
