// <auto-generated />
using System;
using BnpCashClaudeApp.Persistence.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnpCashClaudeApp.Persistence.Migrations
{
    [DbContext(typeof(NavigationDbContext))]
    partial class NavigationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Persian_100_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyNationalId")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerLevel")
                        .HasColumnType("int");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EconomicCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MembershipDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyNationalId");

                    b.HasIndex("CustomerCode")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("NationalId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("tblCustomers", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ContactType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Messenger")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblCustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("tblCustomerId");

                    b.ToTable("tblCustomerContacts", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerSoftware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActivationCount")
                        .HasColumnType("int");

                    b.Property<string>("CustomSettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("EndDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("InstalledVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastActivationDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastActivationIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LicenseCount")
                        .HasColumnType("int");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaxActivations")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("StartDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblPlanId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblSoftwareId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("tblPlanId");

                    b.HasIndex("tblSoftwareId");

                    b.HasIndex("tblCustomerId", "tblSoftwareId");

                    b.ToTable("tblCustomerSoftwares", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerSoftwareDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConnectedDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<int>("UsageType")
                        .HasColumnType("int");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblCustomerSoftwareId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblDbId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("tblDbId");

                    b.HasIndex("tblCustomerSoftwareId", "tblDbId")
                        .IsUnique();

                    b.ToTable("tblCustomerSoftwareDbs", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CurrentSizeMB")
                        .HasColumnType("int");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DbCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DbType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedConnectionString")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Environment")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<string>("LastBackupDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastConnectionTestDate")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool?>("LastConnectionTestResult")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxSizeMB")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("TenantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("tblCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblSoftwareId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DbCode")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("tblCustomerId");

                    b.HasIndex("tblSoftwareId");

                    b.ToTable("tblDbs", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FeaturesJson")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxBranchCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDailyTransactions")
                        .HasColumnType("int");

                    b.Property<int?>("MaxDbSizeMB")
                        .HasColumnType("int");

                    b.Property<int?>("MaxMemberCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUserCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MonthlyPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("YearlyPrice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblSoftwareId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("tblSoftwareId", "Code")
                        .IsUnique();

                    b.ToTable("tblPlans", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblSoftware", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CurrentVersion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("tblSoftwares", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GrpCode")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("tblShobeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblGrps_PublicId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblGrps_tblShobeId");

                    b.ToTable("tblGrps");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrpPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GrantedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblGrpId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblPermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tblPermissionId");

                    b.HasIndex("tblGrpId", "tblPermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblGrpPermissions_tblGrpId_tblPermissionId");

                    b.ToTable("tblGrpPermissions", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMenu")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("tblSoftwareId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblMenus_PublicId");

                    b.HasIndex("tblSoftwareId")
                        .HasDatabaseName("IX_tblMenus_tblSoftwareId");

                    b.ToTable("tblMenus");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenuPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblMenuId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblPermissionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tblPermissionId");

                    b.HasIndex("tblMenuId", "tblPermissionId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblMenuPermissions_tblMenuId_tblPermissionId");

                    b.ToTable("tblMenuPermissions", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblPermissions_PublicId");

                    b.HasIndex("Resource", "Action");

                    b.ToTable("tblPermissions", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("ShobeCode")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("tblCustomerId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblShobes_PublicId");

                    b.HasIndex("ShobeCode")
                        .IsUnique()
                        .HasDatabaseName("IX_tblShobes_ShobeCode");

                    b.HasIndex("tblCustomerId")
                        .HasDatabaseName("IX_tblShobes_tblCustomerId");

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("tblShobes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobeSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TblShobeId")
                        .HasColumnType("bigint");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("TblShobeId")
                        .HasDatabaseName("IX_tblShobeSettings_TblShobeId");

                    b.HasIndex("SettingKey", "TblShobeId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblShobeSettings_SettingKey_TblShobeId")
                        .HasFilter("[TblShobeId] IS NOT NULL");

                    b.ToTable("tblShobeSettings", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMfaEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LastLoginAt")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaEnabledAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaLastUsedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaRecoveryCodes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MfaSecretKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordLastChangedAt")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProfilePictureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserCode")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("tblCustomerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("tblShobeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblUsers_PublicId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_tblUsers_UserName");

                    b.HasIndex("tblCustomerId")
                        .HasDatabaseName("IX_tblUsers_tblCustomerId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblUsers_tblShobeId");

                    b.ToTable("tblUsers");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUserGrp", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignmentDate")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblGrpId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tblGrpId");

                    b.HasIndex("tblUserId", "tblGrpId")
                        .IsUnique();

                    b.ToTable("tblUserGrps");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.CryptographicKeyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DestroyedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestructionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EncryptedKeyValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EncryptionIV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EncryptionMAC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GracePeriodEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("KeyLengthBits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PreviousKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ReplacedByKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique()
                        .HasDatabaseName("IX_CryptographicKeys_KeyId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_CryptographicKeys_PublicId");

                    b.HasIndex("Purpose")
                        .HasDatabaseName("IX_CryptographicKeys_Purpose");

                    b.HasIndex("Purpose", "Status")
                        .HasDatabaseName("IX_CryptographicKeys_Purpose_Status");

                    b.ToTable("CryptographicKeys", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.PasswordHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SetAt")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_PasswordHistory_PublicId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "PasswordHash");

                    b.ToTable("PasswordHistory", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IntegrityHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_PublicId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRevoked", "IsUsed");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.SecuritySubsystem.SecuritySetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SettingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_SecuritySettings_PublicId");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("SecuritySettings", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerContact", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", "Customer")
                        .WithMany("Contacts")
                        .HasForeignKey("tblCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerSoftware", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", "Customer")
                        .WithMany("CustomerSoftwares")
                        .HasForeignKey("tblCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblPlan", "Plan")
                        .WithMany("CustomerSoftwares")
                        .HasForeignKey("tblPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblSoftware", "Software")
                        .WithMany("CustomerSoftwares")
                        .HasForeignKey("tblSoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Plan");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerSoftwareDb", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerSoftware", "CustomerSoftware")
                        .WithMany("CustomerSoftwareDbs")
                        .HasForeignKey("tblCustomerSoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblDb", "Db")
                        .WithMany("CustomerSoftwareDbs")
                        .HasForeignKey("tblDbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerSoftware");

                    b.Navigation("Db");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblDb", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", "Customer")
                        .WithMany("Databases")
                        .HasForeignKey("tblCustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblSoftware", "Software")
                        .WithMany("Databases")
                        .HasForeignKey("tblSoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblPlan", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblSoftware", "Software")
                        .WithMany("Plans")
                        .HasForeignKey("tblSoftwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", "Shobe")
                        .WithMany("Groups")
                        .HasForeignKey("tblShobeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("Shobe");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrpPermission", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "tblGrp")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("tblGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", "tblPermission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("tblPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblGrp");

                    b.Navigation("tblPermission");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblSoftware", "Software")
                        .WithMany("Menus")
                        .HasForeignKey("tblSoftwareId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenuPermission", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", "tblMenu")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("tblMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", "tblPermission")
                        .WithMany("MenuPermissions")
                        .HasForeignKey("tblPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblMenu");

                    b.Navigation("tblPermission");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", "Customer")
                        .WithMany("Shobes")
                        .HasForeignKey("tblCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobeSetting", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", "TblShobe")
                        .WithMany()
                        .HasForeignKey("TblShobeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TblShobe");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", "Customer")
                        .WithMany("Users")
                        .HasForeignKey("tblCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", "Shobe")
                        .WithMany("Users")
                        .HasForeignKey("tblShobeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Shobe");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUserGrp", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", "tblGrp")
                        .WithMany("UserGroups")
                        .HasForeignKey("tblGrpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblUser", "tblUser")
                        .WithMany()
                        .HasForeignKey("tblUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tblGrp");

                    b.Navigation("tblUser");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomer", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("CustomerSoftwares");

                    b.Navigation("Databases");

                    b.Navigation("Shobes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblCustomerSoftware", b =>
                {
                    b.Navigation("CustomerSoftwareDbs");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblDb", b =>
                {
                    b.Navigation("CustomerSoftwareDbs");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblPlan", b =>
                {
                    b.Navigation("CustomerSoftwares");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.ManagementSubsystem.tblSoftware", b =>
                {
                    b.Navigation("CustomerSoftwares");

                    b.Navigation("Databases");

                    b.Navigation("Menus");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblGrp", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblPermission", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("MenuPermissions");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.NavigationSubsystem.tblShobe", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Groups");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
