// <auto-generated />
using System;
using BnpCashClaudeApp.Persistence.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnpCashClaudeApp.Persistence.Migrations.CashMigrations
{
    [DbContext(typeof(CashDbContext))]
    [Migration("20260203110000_AddTblSarfaslType")]
    partial class AddTblSarfaslType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblAzaNoe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CodeHoze")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("PishFarz")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblShobeId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblTafsiliTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblAzaNoes_PublicId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblAzaNoes_tblShobeId");

                    b.HasIndex("tblTafsiliTypeId")
                        .HasDatabaseName("IX_tblAzaNoes_tblTafsiliTypeId");

                    b.HasIndex("IsDeleted", "IsActive")
                        .HasDatabaseName("IX_tblAzaNoes_IsDeleted_IsActive");

                    b.HasIndex("tblShobeId", "CodeHoze")
                        .HasDatabaseName("IX_tblAzaNoes_tblShobeId_CodeHoze");

                    b.ToTable("tblAzaNoes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblCombo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GrpCode")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("GrpCode")
                        .HasDatabaseName("IX_tblCombos_GrpCode");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblCombos_PublicId");

                    b.ToTable("tblCombos", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfaslType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblSarfaslTypes_PublicId");

                    b.ToTable("tblSarfaslTypes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CodeTafsiliType")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblShobeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CodeTafsiliType")
                        .IsUnique()
                        .HasDatabaseName("IX_tblTafsiliTypes_CodeTafsiliType");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblTafsiliTypes_PublicId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblTafsiliTypes_tblShobeId");

                    b.HasIndex("IsDeleted", "IsActive")
                        .HasDatabaseName("IX_tblTafsiliTypes_IsDeleted_IsActive");

                    b.ToTable("tblTafsiliTypes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblAzaNoe", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", "TafsiliType")
                        .WithMany("AzaNoeList")
                        .HasForeignKey("tblTafsiliTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TafsiliType");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", b =>
                {
                    b.Navigation("AzaNoeList");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
