// <auto-generated />
using System;
using BnpCashClaudeApp.Persistence.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnpCashClaudeApp.Persistence.Migrations.CashMigrations
{
    [DbContext(typeof(CashDbContext))]
    partial class CashDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:Collation", "Persian_100_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblAzaNoe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CodeHoze")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("PishFarz")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblShobeId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblTafsiliTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblAzaNoes_PublicId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblAzaNoes_tblShobeId");

                    b.HasIndex("tblTafsiliTypeId")
                        .HasDatabaseName("IX_tblAzaNoes_tblTafsiliTypeId");

                    b.HasIndex("IsDeleted", "IsActive")
                        .HasDatabaseName("IX_tblAzaNoes_IsDeleted_IsActive");

                    b.HasIndex("tblShobeId", "CodeHoze")
                        .HasDatabaseName("IX_tblAzaNoes_tblShobeId_CodeHoze");

                    b.ToTable("tblAzaNoes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblCombo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GrpCode")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("GrpCode")
                        .HasDatabaseName("IX_tblCombos_GrpCode");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblCombos_PublicId");

                    b.ToTable("tblCombos", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfasl", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeSarfasl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MizanEtebarBedehkar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MizanEtebarBestankar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,0)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("NotShowInTaraz")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<int?>("TedadArghamZirGrp")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("WithJoze")
                        .HasColumnType("bit");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long?>("tblComboIdControlAmaliat")
                        .HasColumnType("bigint");

                    b.Property<long?>("tblComboIdVazeiatZirGrp")
                        .HasColumnType("bigint");

                    b.Property<long?>("tblSarfaslProtocolId")
                        .HasColumnType("bigint");

                    b.Property<long?>("tblSarfaslTypeId")
                        .HasColumnType("bigint");

                    b.Property<long>("tblShobeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("Id");

                    b.HasIndex("CodeSarfasl")
                        .HasDatabaseName("IX_tblSarfasls_CodeSarfasl");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_tblSarfasls_ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblSarfasls_PublicId");

                    b.HasIndex("tblSarfaslProtocolId")
                        .HasDatabaseName("IX_tblSarfasls_tblSarfaslProtocolId");

                    b.HasIndex("tblSarfaslTypeId")
                        .HasDatabaseName("IX_tblSarfasls_tblSarfaslTypeId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblSarfasls_tblShobeId");

                    b.ToTable("tblSarfasls", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfaslProtocol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultSarfaslJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_tblSarfaslProtocols_Code");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblSarfaslProtocols_PublicId");

                    b.ToTable("tblSarfaslProtocols", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfaslType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblSarfaslTypes_PublicId");

                    b.ToTable("tblSarfaslTypes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CodeTafsiliType")
                        .HasColumnType("int");

                    b.Property<string>("IntegrityHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<long>("TblUserGrpIdInsert")
                        .HasColumnType("bigint");

                    b.Property<long?>("TblUserGrpIdLastEdit")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZamanInsert")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("ZamanLastEdit")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("tblShobeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CodeTafsiliType")
                        .IsUnique()
                        .HasDatabaseName("IX_tblTafsiliTypes_CodeTafsiliType");

                    b.HasIndex("ParentId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("IX_tblTafsiliTypes_PublicId");

                    b.HasIndex("tblShobeId")
                        .HasDatabaseName("IX_tblTafsiliTypes_tblShobeId");

                    b.HasIndex("IsDeleted", "IsActive")
                        .HasDatabaseName("IX_tblTafsiliTypes_IsDeleted_IsActive");

                    b.ToTable("tblTafsiliTypes", (string)null);
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblAzaNoe", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", "TafsiliType")
                        .WithMany("AzaNoeList")
                        .HasForeignKey("tblTafsiliTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TafsiliType");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfasl", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfasl", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfaslProtocol", "SarfaslProtocol")
                        .WithMany()
                        .HasForeignKey("tblSarfaslProtocolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfaslType", "SarfaslType")
                        .WithMany()
                        .HasForeignKey("tblSarfaslTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");

                    b.Navigation("SarfaslProtocol");

                    b.Navigation("SarfaslType");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", b =>
                {
                    b.HasOne("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblSarfasl", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("BnpCashClaudeApp.Domain.Entities.CashSubsystem.tblTafsiliType", b =>
                {
                    b.Navigation("AzaNoeList");

                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
